

package net.kingdomsofarden.andrew2060.market.util;

import org.bukkit.Material;

public enum ItemCategory {
    BLOCKS,
    ORES,
    PLANTS,
    FOOD,
    REDSTONE,
    TOOLS,
    ARMOR,
    AMMO,
    ALCHEMY,
    MAGIC,
    BLACKSMITHING,
    TRAVEL,
    SPAWNEGG,
    MISC,
    NONE;
    
    public static ItemCategory findCategory(Material mat) {
        switch(mat) {
        
        case ACTIVATOR_RAIL:
            return ItemCategory.TRAVEL;
        case ANVIL:
            return ItemCategory.BLACKSMITHING;
        case APPLE:
            return ItemCategory.FOOD;
        case ARROW:
            return ItemCategory.AMMO;
        case BAKED_POTATO:
            return ItemCategory.FOOD;
        case BEACON:
            return ItemCategory.MAGIC;
        case BED:
            return ItemCategory.BLOCKS;
        case BIRCH_WOOD_STAIRS:
            return ItemCategory.BLOCKS;
        case BLAZE_POWDER:
            return ItemCategory.ALCHEMY;
        case BLAZE_ROD:
            return ItemCategory.ALCHEMY;
        case BOAT:
            return ItemCategory.TRAVEL;
        case BONE:
            return ItemCategory.AMMO;
        case BOOK:
            return ItemCategory.MAGIC;
        case BOOKSHELF:
            return ItemCategory.BLOCKS;
        case BOOK_AND_QUILL:
            return ItemCategory.MAGIC;
        case BOW:
            return ItemCategory.TOOLS;
        case BOWL:
            return ItemCategory.FOOD;
        case BREAD:
            return ItemCategory.FOOD;
        case BREWING_STAND_ITEM:
            return ItemCategory.ALCHEMY;
        case BRICK:
            return ItemCategory.BLOCKS;
        case BRICK_STAIRS:
            return ItemCategory.BLOCKS;
        case BROWN_MUSHROOM:
            return ItemCategory.FOOD;
        case BUCKET:
            return ItemCategory.MISC;
        case CACTUS:
            return ItemCategory.PLANTS;
        case CAKE:
            return ItemCategory.FOOD;
        case CARPET:
            return ItemCategory.BLOCKS;
        case CARROT_ITEM:
            return ItemCategory.FOOD;
        case CARROT_STICK:
            return ItemCategory.MISC;
        case CAULDRON_ITEM:
            return ItemCategory.ALCHEMY;
        case CHAINMAIL_BOOTS:
            return ItemCategory.ARMOR;
        case CHAINMAIL_CHESTPLATE:
            return ItemCategory.ARMOR;
        case CHAINMAIL_HELMET:
            return ItemCategory.ARMOR;
        case CHAINMAIL_LEGGINGS:
            return ItemCategory.ARMOR;
        case CHEST:
            return ItemCategory.BLOCKS;
        case CLAY:
            return ItemCategory.BLOCKS;
        case CLAY_BALL:
            return ItemCategory.BLOCKS;
        case CLAY_BRICK:
            return ItemCategory.BLACKSMITHING;
        case COAL:
            return ItemCategory.ORES;
        case COAL_BLOCK:
            return ItemCategory.ORES;
        case COAL_ORE:
            return ItemCategory.ORES;
        case COBBLESTONE:
            return ItemCategory.BLOCKS;
        case COBBLESTONE_STAIRS:
            return ItemCategory.BLOCKS;
        case COBBLE_WALL:
            return ItemCategory.BLOCKS;
        case COCOA:
            return ItemCategory.FOOD;
        case COMPASS:
            return ItemCategory.MISC;
        case COOKED_BEEF:
            return ItemCategory.FOOD;
        case COOKED_CHICKEN:
            return ItemCategory.FOOD;
        case COOKED_FISH:
            return ItemCategory.FOOD;
        case COOKIE:
            return ItemCategory.FOOD;
        case CROPS:
            return ItemCategory.FOOD;
        case DAYLIGHT_DETECTOR:
            return ItemCategory.REDSTONE;
        case DEAD_BUSH:
            return ItemCategory.MISC;
        case DETECTOR_RAIL:
            return ItemCategory.REDSTONE;
        case DIAMOND:
            return ItemCategory.ORES;
        case DIAMOND_AXE:
            return ItemCategory.TOOLS;
        case DIAMOND_BARDING:
            return ItemCategory.ARMOR;
        case DIAMOND_BLOCK:
            return ItemCategory.ORES;
        case DIAMOND_BOOTS:
            return ItemCategory.ARMOR;
        case DIAMOND_CHESTPLATE:
            return ItemCategory.ARMOR;
        case DIAMOND_HELMET:
            return ItemCategory.ARMOR;
        case DIAMOND_HOE:
            return ItemCategory.TOOLS;
        case DIAMOND_LEGGINGS:
            return ItemCategory.ARMOR;
        case DIAMOND_ORE:
            return ItemCategory.ORES;
        case DIAMOND_PICKAXE:
            return ItemCategory.TOOLS;
        case DIAMOND_SPADE:
            return ItemCategory.TOOLS;
        case DIAMOND_SWORD:
            return ItemCategory.TOOLS;
        case DIODE:
            return ItemCategory.REDSTONE;
        case DIRT:
            return ItemCategory.BLOCKS;
        case DISPENSER:
            return ItemCategory.REDSTONE;
        case DOUBLE_STEP:
            return ItemCategory.BLOCKS;
        case DRAGON_EGG:
            return ItemCategory.SPAWNEGG;
        case DROPPER:
            return ItemCategory.REDSTONE;
        case EGG:
            return ItemCategory.SPAWNEGG;
        case EMERALD:
            return ItemCategory.ORES;
        case EMERALD_BLOCK:
            return ItemCategory.ORES;
        case EMERALD_ORE:
            return ItemCategory.ORES;
        case EMPTY_MAP:
            return ItemCategory.MISC;
        case ENCHANTED_BOOK:
            return ItemCategory.MAGIC;
        case ENCHANTMENT_TABLE:
            return ItemCategory.MAGIC;
        case ENDER_CHEST:
            return ItemCategory.BLOCKS;
        case ENDER_PEARL:
            return ItemCategory.MAGIC;
        case ENDER_PORTAL_FRAME:
            return ItemCategory.BLOCKS;
        case ENDER_STONE:
            return ItemCategory.BLOCKS;
        case EXPLOSIVE_MINECART:
            return ItemCategory.TRAVEL;
        case EXP_BOTTLE:
            return ItemCategory.ALCHEMY;
        case EYE_OF_ENDER:
            return ItemCategory.MAGIC;
        case FEATHER:
            return ItemCategory.MISC;
        case FENCE:
            return ItemCategory.BLOCKS;
        case FENCE_GATE:
            return ItemCategory.BLOCKS;
        case FERMENTED_SPIDER_EYE:
            return ItemCategory.ALCHEMY;
        case FIREBALL:
            return ItemCategory.MAGIC;
        case FIREWORK:
            return ItemCategory.MISC;
        case FIREWORK_CHARGE:
            return ItemCategory.MISC;
        case FISHING_ROD:
            return ItemCategory.TOOLS;
        case FLINT:
            return ItemCategory.MISC;
        case FLINT_AND_STEEL:
            return ItemCategory.MISC;
        case FLOWER_POT_ITEM:
            return ItemCategory.BLOCKS;
        case FURNACE:
            return ItemCategory.BLOCKS;
        case GHAST_TEAR:
            return ItemCategory.ALCHEMY;
        case GLASS:
            return ItemCategory.BLOCKS;
        case GLASS_BOTTLE:
            return ItemCategory.ALCHEMY;
        case GLOWSTONE:
            return ItemCategory.ALCHEMY;
        case GLOWSTONE_DUST:
            return ItemCategory.ALCHEMY;
        case GOLDEN_APPLE:
            return ItemCategory.ALCHEMY;
        case GOLDEN_CARROT:
            return ItemCategory.ALCHEMY;
        case GOLD_AXE:
            return ItemCategory.TOOLS;
        case GOLD_BARDING:
            return ItemCategory.ARMOR;
        case GOLD_BOOTS:
            return ItemCategory.ARMOR;
        case GOLD_CHESTPLATE:
            return ItemCategory.ARMOR;
        case GOLD_HELMET:
            return ItemCategory.ARMOR;
        case GOLD_HOE:
            return ItemCategory.TOOLS;
        case GOLD_INGOT:
            return ItemCategory.ORES;
        case GOLD_LEGGINGS:
            return ItemCategory.ARMOR;
        case GOLD_PICKAXE:
            return ItemCategory.TOOLS;
        case GOLD_PLATE:
            return ItemCategory.ARMOR;
        case GOLD_RECORD:
            return ItemCategory.MISC;
        case GOLD_SPADE:
            return ItemCategory.TOOLS;
        case GOLD_SWORD:
            return ItemCategory.TOOLS;
        case GRASS:
            return ItemCategory.BLOCKS;
        case GRAVEL:
            return ItemCategory.BLOCKS;
        case GREEN_RECORD:
            return ItemCategory.MISC;
        case GRILLED_PORK:
            return ItemCategory.FOOD;
        case HARD_CLAY:
            return ItemCategory.BLOCKS;
        case HAY_BLOCK:
            return ItemCategory.BLOCKS;
        case HOPPER:
            return ItemCategory.REDSTONE;
        case HOPPER_MINECART:
            return ItemCategory.TRAVEL;
        case ICE:
            return ItemCategory.BLOCKS;
        case INK_SACK:
            return ItemCategory.ALCHEMY;
        case IRON_AXE:
            return ItemCategory.TOOLS;
        case IRON_BARDING:
            return ItemCategory.ARMOR;
        case IRON_BLOCK:
            return ItemCategory.ORES;
        case IRON_BOOTS:
            return ItemCategory.ARMOR;
        case IRON_CHESTPLATE:
            return ItemCategory.ARMOR;
        case IRON_DOOR:
            return ItemCategory.BLOCKS;
        case IRON_FENCE:
            return ItemCategory.BLOCKS;
        case IRON_HELMET:
            return ItemCategory.ARMOR;
        case IRON_HOE:
            return ItemCategory.TOOLS;
        case IRON_INGOT:
            return ItemCategory.ORES;
        case IRON_LEGGINGS:
            return ItemCategory.ARMOR;
        case IRON_ORE:
            return ItemCategory.ORES;
        case IRON_PICKAXE:
            return ItemCategory.TOOLS;
        case IRON_PLATE:
            return ItemCategory.ARMOR;
        case IRON_SPADE:
            return ItemCategory.TOOLS;
        case IRON_SWORD:
            return ItemCategory.TOOLS;
        case ITEM_FRAME:
            return ItemCategory.BLOCKS;
        case JACK_O_LANTERN:
            return ItemCategory.BLOCKS;
        case JUKEBOX:
            return ItemCategory.BLOCKS;
        case JUNGLE_WOOD_STAIRS:
            return ItemCategory.BLOCKS;
        case LADDER:
            return ItemCategory.BLOCKS;
        case LAPIS_BLOCK:
            return ItemCategory.ORES;
        case LAPIS_ORE:
            return ItemCategory.ORES;
        case LAVA_BUCKET:
            return ItemCategory.MISC;
        case LEASH:
            return ItemCategory.MISC;
        case LEATHER:
            return ItemCategory.BLACKSMITHING;
        case LEATHER_BOOTS:
            return ItemCategory.ARMOR;
        case LEATHER_CHESTPLATE:
            return ItemCategory.ARMOR;
        case LEATHER_HELMET:
            return ItemCategory.ARMOR;
        case LEATHER_LEGGINGS:
            return ItemCategory.ARMOR;
        case LEAVES:
            return ItemCategory.BLOCKS;
        case LEVER:
            return ItemCategory.REDSTONE;
        case LOG:
            return ItemCategory.BLOCKS;
        case LONG_GRASS:
            return ItemCategory.PLANTS;
        case MAGMA_CREAM:
            return ItemCategory.ALCHEMY;
        case MAP:
            return ItemCategory.TRAVEL;
        case MELON:
            return ItemCategory.FOOD;
        case MELON_BLOCK:
            return ItemCategory.FOOD;
        case MELON_SEEDS:
            return ItemCategory.PLANTS;
        case MILK_BUCKET:
            return ItemCategory.FOOD;
        case MINECART:
            return ItemCategory.TRAVEL;
        case MONSTER_EGG:
            return ItemCategory.SPAWNEGG;
        case MONSTER_EGGS:
            return ItemCategory.SPAWNEGG;
        case MOSSY_COBBLESTONE:
            return ItemCategory.BLOCKS;
        case MUSHROOM_SOUP:
            return ItemCategory.FOOD;
        case MYCEL:
            return ItemCategory.BLOCKS;
        case NAME_TAG:
            return ItemCategory.MISC;
        case NETHERRACK:
            return ItemCategory.BLOCKS;
        case NETHER_BRICK:
            return ItemCategory.BLOCKS;
        case NETHER_BRICK_ITEM:
            return ItemCategory.BLOCKS;
        case NETHER_BRICK_STAIRS:
            return ItemCategory.BLOCKS;
        case NETHER_FENCE:
            return ItemCategory.BLOCKS;
        case NETHER_STALK:
            return ItemCategory.ALCHEMY;
        case NETHER_STAR:
            return ItemCategory.MAGIC;
        case NETHER_WARTS:
            return ItemCategory.ALCHEMY;
        case NOTE_BLOCK:
            return ItemCategory.BLOCKS;
        case OBSIDIAN:
            return ItemCategory.BLOCKS;
        case PAINTING:
            return ItemCategory.BLOCKS;
        case PAPER:
            return ItemCategory.MAGIC;
        case PISTON_BASE:
            return ItemCategory.REDSTONE;
        case PISTON_STICKY_BASE:
            return ItemCategory.REDSTONE;
        case POISONOUS_POTATO:
            return ItemCategory.ALCHEMY;
        case PORK:
            return ItemCategory.FOOD;
        case POTATO_ITEM:
            return ItemCategory.FOOD;
        case POTION:
            return ItemCategory.ALCHEMY;
        case POWERED_MINECART:
            return ItemCategory.TRAVEL;
        case POWERED_RAIL:
            return ItemCategory.REDSTONE;
        case PUMPKIN:
            return ItemCategory.BLOCKS;
        case PUMPKIN_PIE:
            return ItemCategory.FOOD;
        case PUMPKIN_SEEDS:
            return ItemCategory.PLANTS;
        case QUARTZ:
            return ItemCategory.ORES;
        case QUARTZ_BLOCK:
            return ItemCategory.BLOCKS;
        case QUARTZ_ORE:
            return ItemCategory.ORES;
        case QUARTZ_STAIRS:
            return ItemCategory.BLOCKS;
        case RAILS:
            return ItemCategory.TRAVEL;
        case RAW_BEEF:
            return ItemCategory.FOOD;
        case RAW_CHICKEN:
            return ItemCategory.FOOD;
        case RAW_FISH:
            return ItemCategory.FOOD;
        case RECORD_10:
            return ItemCategory.MISC;
        case RECORD_11:
            return ItemCategory.MISC;
        case RECORD_12:
            return ItemCategory.MISC;
        case RECORD_3:
            return ItemCategory.MISC;
        case RECORD_4:
            return ItemCategory.MISC;
        case RECORD_5:
            return ItemCategory.MISC;
        case RECORD_6:
            return ItemCategory.MISC;
        case RECORD_7:
            return ItemCategory.MISC;
        case RECORD_8:
            return ItemCategory.MISC;
        case RECORD_9:
            return ItemCategory.MISC;
        case REDSTONE:
            return ItemCategory.REDSTONE;
        case REDSTONE_BLOCK:
            return ItemCategory.REDSTONE;
        case REDSTONE_COMPARATOR:
            return ItemCategory.REDSTONE;
        case REDSTONE_COMPARATOR_OFF:
            return ItemCategory.REDSTONE;
        case REDSTONE_COMPARATOR_ON:
            return ItemCategory.REDSTONE;
        case REDSTONE_LAMP_OFF:
            return ItemCategory.REDSTONE;
        case REDSTONE_LAMP_ON:
            return ItemCategory.REDSTONE;
        case REDSTONE_ORE:
            return ItemCategory.REDSTONE;
        case REDSTONE_TORCH_OFF:
            return ItemCategory.REDSTONE;
        case REDSTONE_TORCH_ON:
            return ItemCategory.REDSTONE;
        case REDSTONE_WIRE:
            return ItemCategory.REDSTONE;
        case RED_MUSHROOM:
            return ItemCategory.FOOD;
        case RED_ROSE:
            return ItemCategory.PLANTS;
        case ROTTEN_FLESH:
            return ItemCategory.ALCHEMY;
        case SADDLE:
            return ItemCategory.MISC;
        case SAND:
            return ItemCategory.BLOCKS;
        case SANDSTONE:
            return ItemCategory.BLOCKS;
        case SANDSTONE_STAIRS:
            return ItemCategory.BLOCKS;
        case SAPLING:
            return ItemCategory.PLANTS;
        case SEEDS:
            return ItemCategory.PLANTS;
        case SHEARS:
            return ItemCategory.TOOLS;
        case SIGN:
            return ItemCategory.BLOCKS;
        case SKULL:
            return ItemCategory.ALCHEMY;
        case SKULL_ITEM:
            return ItemCategory.ALCHEMY;
        case SLIME_BALL:
            return ItemCategory.ALCHEMY;
        case SMOOTH_BRICK:
            return ItemCategory.BLOCKS;
        case SMOOTH_STAIRS:
            return ItemCategory.BLOCKS;
        case SNOW:
            return ItemCategory.BLOCKS;
        case SNOW_BALL:
            return ItemCategory.BLOCKS;
        case SNOW_BLOCK:
            return ItemCategory.BLOCKS;
        case SOUL_SAND:
            return ItemCategory.BLOCKS;
        case SPECKLED_MELON:
            return ItemCategory.ALCHEMY;
        case SPIDER_EYE:
            return ItemCategory.ALCHEMY;
        case SPONGE:
            return ItemCategory.BLOCKS;
        case SPRUCE_WOOD_STAIRS:
            return ItemCategory.BLOCKS;
        case STAINED_CLAY:
            return ItemCategory.BLOCKS;
        case STEP:
            return ItemCategory.BLOCKS;
        case STICK:
            return ItemCategory.TOOLS;
        case STONE:
            return ItemCategory.BLOCKS;
        case STONE_AXE:
            return ItemCategory.TOOLS;
        case STONE_BUTTON:
            return ItemCategory.REDSTONE;
        case STONE_HOE:
            return ItemCategory.TOOLS;
        case STONE_PICKAXE:
            return ItemCategory.TOOLS;
        case STONE_PLATE:
            return ItemCategory.REDSTONE;
        case STONE_SPADE:
            return ItemCategory.TOOLS;
        case STONE_SWORD:
            return ItemCategory.TOOLS;
        case STORAGE_MINECART:
            return ItemCategory.TRAVEL;
        case STRING:
            return ItemCategory.MISC;
        case SUGAR:
            return ItemCategory.ALCHEMY;
        case SUGAR_CANE:
            return ItemCategory.PLANTS;
        case SULPHUR:
            return ItemCategory.AMMO;
        case THIN_GLASS:
            return ItemCategory.BLOCKS;
        case TNT:
            return ItemCategory.AMMO;
        case TORCH:
            return ItemCategory.MISC;
        case TRAPPED_CHEST:
            return ItemCategory.BLOCKS;
        case TRAP_DOOR:
            return ItemCategory.BLOCKS;
        case TRIPWIRE:
            return ItemCategory.REDSTONE;
        case TRIPWIRE_HOOK:
            return ItemCategory.REDSTONE;
        case VINE:
            return ItemCategory.BLOCKS;
        case WATCH:
            return ItemCategory.REDSTONE;
        case WATER_BUCKET:
            return ItemCategory.MISC;
        case WATER_LILY:
            return ItemCategory.PLANTS;
        case WEB:
            return ItemCategory.BLOCKS;
        case WHEAT:
            return ItemCategory.FOOD;
        case WOOD:
            return ItemCategory.BLOCKS;
        case WOODEN_DOOR:
            return ItemCategory.BLOCKS;
        case WOOD_AXE:
            return ItemCategory.TOOLS;
        case WOOD_BUTTON:
            return ItemCategory.REDSTONE;
        case WOOD_DOOR:
            return ItemCategory.BLOCKS;
        case WOOD_DOUBLE_STEP:
            return ItemCategory.BLOCKS;
        case WOOD_HOE:
            return ItemCategory.TOOLS;
        case WOOD_PICKAXE:
            return ItemCategory.TOOLS;
        case WOOD_PLATE:
            return ItemCategory.REDSTONE;
        case WOOD_SPADE:
            return ItemCategory.TOOLS;
        case WOOD_STAIRS:
            return ItemCategory.BLOCKS;
        case WOOD_STEP:
            return ItemCategory.BLOCKS;
        case WOOD_SWORD:
            return ItemCategory.TOOLS;
        case WOOL:
            return ItemCategory.BLOCKS;
        case WORKBENCH:
            return ItemCategory.BLOCKS;
        case WRITTEN_BOOK:
            return ItemCategory.MISC;
        case YELLOW_FLOWER:
            return ItemCategory.PLANTS;
        default:
            return ItemCategory.NONE;
        
        }
        
    }
    
}

